# Generated by Django 5.0.6 on 2024-06-10 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantCare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myplant',
            old_name='plant_genre',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='planttype',
            old_name='genre',
            new_name='species',
        ),
        migrations.AddField(
            model_name='replanting',
            name='new_soil_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='new_soil_type', to='PlantCare.soil'),
        ),
        migrations.AddField(
            model_name='replanting',
            name='old_soil_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='old_soil_type', to='PlantCare.soil'),
        ),
        migrations.AlterField(
            model_name='myplant',
            name='light_requirements',
            field=models.IntegerField(choices=[(1, 'bardzo jasne'), (2, 'jasne, światło rozproszone'), (3, 'półcieniste'), (4, 'cieniste')], default=None),
        ),
        migrations.AlterField(
            model_name='myplant',
            name='soil_humidity',
            field=models.IntegerField(choices=[(1, 'długo utrzymujące wilgoć'), (2, 'przepuszczalne'), (3, 'wysoko przepuszczalne')], default=None),
        ),
        migrations.AlterField(
            model_name='replanting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soil_type',
            field=models.IntegerField(choices=[(1, 'podłoże dla roślin wilgociolubnych'), (2, 'podłoże uniwersalne'), (3, 'podłoże dla roślin obrazkowatych'), (4, 'podłoże dla epifitów'), (5, 'podłoże dla roślin sucholubnych'), (6, 'podłoże produkcyjne')]),
        ),
    ]
