# Generated by Django 5.0.6 on 2024-06-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantCare', '0004_watering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='plant',
            field=models.ForeignKey(help_text='Wybierz roślinę do podlewania', on_delete=django.db.models.deletion.CASCADE, to='PlantCare.myplant'),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_amount',
            field=models.DecimalField(decimal_places=2, help_text='Podaj ilość wlanej wody w ml', max_digits=5),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_content',
            field=models.DecimalField(decimal_places=2, help_text='Sprawdź za pomocą higrometru wilgotność gleby', max_digits=5),
        ),
    ]
